updating worflow depedency

diff --git a/.github/workflows/cicd-3-deploy.yaml b/.github/workflows/cicd-3-deploy.yaml
--- a/.github/workflows/cicd-3-deploy.yaml
+++ b/.github/workflows/cicd-3-deploy.yaml
@@ -16,6 +16,18 @@ on:
           - prod
 
 jobs:
+  validate-main-branch:
+    name: "Validate deployment from main branch"
+    runs-on: ubuntu-latest
+    steps:
+    - name: "Check branch"
+      run: |
+        if [ "${{ github.ref }}" != "refs/heads/main" ]; then
+          echo "ERROR: This workflow can only be run from the 'main' branch." >&2
+          echo "Current branch: ${{ github.ref }}" >&2
+          exit 1
+        fi
+        echo "bypassing the checks temporarily for testing"
   metadata:
     name: "Set CI/CD metadata"
     runs-on: ubuntu-latest
@@ -57,16 +69,8 @@ jobs:
           export VERSION="${{ steps.variables.outputs.version }}"
           export TAG="${{ steps.variables.outputs.tag }}"
           make list-variables
-  deploy:
-    name: "Deploy to an environment"
-    runs-on: ubuntu-latest
-    needs: [metadata]
-    timeout-minutes: 10
-    steps:
-      - name: "Checkout code"
-        uses: actions/checkout@v4
   infra-deploy:
-    needs: [deploy]
+    needs: [terraform-validate]
     uses: ./.github/workflows/infra-deploy.yaml
     with:
       environment: ${{ inputs.environment }}
