fixed yaml syntx

diff --git a/.github/workflows/infra-deploy.yaml b/.github/workflows/infra-deploy.yaml
--- a/.github/workflows/infra-deploy.yaml
+++ b/.github/workflows/infra-deploy.yaml
@@ -23,13 +23,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: "Check branch"
-        run: |
-          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
-            echo "ERROR: This workflow can only be run from the 'main' branch." >&2
-            echo "Current branch: ${{ github.ref }}" >&2
-            exit 1
-          fi
-          echo "bypassing the checks temporarily for testing"
+      run: |
+        if [ "${{ github.ref }}" != "refs/heads/main" ]; then
+          echo "ERROR: This workflow can only be run from the 'main' branch." >&2
+          echo "Current branch: ${{ github.ref }}" >&2
+          exit 1
+        fi
+        echo "bypassing the checks temporarily for testing"
   metadata:
     name: "Set CI/CD metadata"
     needs: [validate-main-branch]
